export const SEND_CODE = 'SEND_CODE';
export const VERIFY_CODE = 'VERIFY_CODE';
export const RESEND_CODE = 'VERIFY_CODE';
export const HANDLE_TEXT_CHANGE_NUMBER = 'HANDLE_TEXT_CHANGE_NUMBER';
export const HANDLE_TEXT_CHANGE_CODE = 'HANDLE_TEXT_CHANGE_CODE';