export const SEND_PHONE_NO = 'SEND_PHONE_NO';
export const SEND_CODE = 'SEND_CODE';
export const VERIFY_CODE = 'VERIFY_CODE';
export const RESEND_CODE = 'RESEND_CODE';
export const REGISTER_CUSTOMER = 'REGISTER_CUSTOMER';
export const HANDLE_TEXT_CHANGE_AUTH = 'HANDLE_TEXT_CHANGE_AUTH';